### ISSUE TITLE
Difficulty Levels

### ISSUE THREAD

**Issue by amayuelas** [PeterGriffinJin/Graph-CoT#6]
The paper mentions the question are categorized in 3 levels: easy, medium and hard. 
But the dataset does not contain such information. How can we know the difficulty level for each question?

**Comment by PeterGriffinJin** [comment]
Hi Alfonso,

Thanks for asking!

You can find the data with the difficulty level added here: https://drive.google.com/drive/folders/1wRHgRf3FJ0BBZvYO8krWGoDIgXUyem4c?usp=sharing

At this moment, there is an internal error in huggingface data hub and we cannot directly update the data there. We will update it there after this issue is solved by HF people.

Feel free to let me know if you have any other questions!

Best,
Bowen

**Comment by PeterGriffinJin** [comment]
The datasets on huggingface data hub are also updated. :)
